### ISSUE TITLE
Create #ArtProject Website based on Invision Design

### ISSUE THREAD

**Issue by andytudhope** [status-im/artproject#1]
This is is fairly straightforward, though will likely take at least a day or two to code up. Simply put, we need someone to build the website for the #ArtProject from scratch based on the Invision docs below.

The design prototype can be found at:
https://invis.io/R6F7UY5CQ#/269818683_Art_Project

The layout was designed with flexbox in mind so its pretty simple to code up in terms of html/css. Each page section would have a 100vw and 100vh.
 
The only point of concern is finding someone with a good grasp of js / jquery to really pull together the intended animations / interactions.

Further details on exactly what these are will be provided on request.

**Comment by status-open-bounty** [comment]
Balance: 0.000000 ETH
Tokens: SNT: 2500.00
Contract address: [0x3d2f821325b43ef91f9da5bf872a4df1c7195dc0](https://etherscan.io/address/0x3d2f821325b43ef91f9da5bf872a4df1c7195dc0)
Network: Mainnet
Paid to: wswidzinski
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by maciejmatu** [comment]
Hey Guys, we can take care of this. Could you provide further info on how it should look? We are front-end developers, so it's our day to day duty, to code things that look great :)

**Comment by wswidzinski** [comment]
^ I'm the second guy, we could start today if you will give us more details.

**Comment by andytudhope** [comment]
Fantastic! I have asked Aqeel, the designer, to come and provide more details here. What exactly do you guys need beyond those invision docs? If I were you, I'd start with the basic layout stuff and then, by the time that is done, Aqeel should have stopped by here to provide further info on what he expects the animations to do.

**Comment by maciejmatu** [comment]
First of all, are there any responsive designs? Also if you have any sketch files of the designs, and can send it over it would be great, because we can't measure distances between items in InVision easily 😄 

Oh, and you could tell what fonts you used. I can't check it in the InVision design.

**Comment by qnou** [comment]
Hey guys, it's a PSD based design, invision inspect will also provide you with the necessary information if need be. As you can see the layout is simple enough to be made responsive using the flexbox property so that shouldn't be an issue. I can step in and provide guidance for the layout adjustments for mobile. However, we need someone with a strong grasp on js to pull off the interactions. 

Would it be possible to see some work? My first exposure to the bounty system so don't know what the proper etiquette is. Perhaps @andytudhope can help guide here.

**Comment by maciejmatu** [comment]
Js is not a problem. I assume by interactions, you mean entry, hover and clicking animations. I was recently working on an interactive 3d globe with interactions. You can see it on the right side of the page when you scroll down a bit. http://akademeia.edu.pl/en/

**Comment by andytudhope** [comment]
Perfect, thanks for answering here @qnou! Yeah, generally we leave these open, but seeing as @maciejmatu and @wswidzinski have answered so quickly, we can "lock" it for them if you are happy with the example supplied and feel like you can explain what is needed over email, or here, or your preferred method of communication (i.e. we will not accept submissions from anyone else from the time this comment is posted).

**Comment by qnou** [comment]
@andytudhope thanks, just wanted to make sure no one was wasting their time.

@maciejmatu Correct, and seamless page transitions. In addition, we want to do some cool things on the pages themselves for the teams page, for eg I wanted the team members profiles to be scroll-able and float in the canvas and interact in a similar manner to something like http://andyweiart.com/ when you scroll through. If you think you can execute something of that quality or better let me know.

In addition the top left image is actually an interactive GLCANVAS which I've already done. So we want to match the rest of the site.

If @maciejmatu and @wswidzinski feel comfortable with what is involved, we can lock it and move. I won't be able to send the psd until later in the night. But can provide enough information in the meantime to start the html side of things. Can continue talks on email or an appropriate riot or slack channel.

Google Fonts: RubikMonoOne for the title
Body: Work Sans various weights.

**Comment by maciejmatu** [comment]
I think we can manage to make this. We will start today with setting up the environment and basic structure. You can choose the communication channel I guess. I can give you our emails, but I don't want to post them here, on a public thread.
